#!/bin/sh
# after git init; mv .git .git-$1
g=$HOME/.git-$1
gd=$HOME/.git-distributed

test -e $g/info/exclude && rm $g/info/exclude
ln -sv $gd/excludes/$1 $g/info/exclude

test -e $g/config && rm $g/config
ln -sv $gd/configs/$1 $g/config
